import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
await page.goto((process.env.E2E_URL || 'http://localhost:4175') + '/');
await page.click('role=tab[name="Builder"]'); await page.waitForTimeout(600);
const pct = () => page.locator('.zoombar .pct').innerText();
console.log('départ', await pct());
await page.click('[aria-label="Zoom in (+ key)"]'); await page.waitForTimeout(300); console.log('bouton +', await pct());
await page.keyboard.press('+'); await page.waitForTimeout(300); console.log('touche +', await pct());
await page.mouse.move(800, 500); for (let i = 0; i < 6; i++) { await page.mouse.wheel(0, -200); await page.waitForTimeout(60); } await page.waitForTimeout(300); console.log('molette', await pct());
await page.keyboard.press('1'); await page.waitForTimeout(300); console.log('touche 1', await pct());
await page.keyboard.press('0'); await page.waitForTimeout(400); console.log('touche 0 (ajuster)', await pct());
await page.screenshot({ path: (process.env.E2E_SHOTS || 'e2e/shots') + '/18-zoombar.png' });
await page.click('role=tab[name="Explorer"]'); await page.waitForTimeout(500);
await page.keyboard.press('ArrowUp'); await page.keyboard.press('ArrowUp'); await page.waitForTimeout(1200);
console.log('zoombar Usage:', await page.locator('.zoombar').count());
console.log(errors.join('\n') || 'no errors');
await browser.close();
