import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
page.on('dialog', d => d.accept());
await page.goto((process.env.E2E_URL || 'http://localhost:4175') + '/');
await page.click('role=tab[name="Builder"]'); await page.waitForTimeout(500);
await page.click('text=Navbar · home'); await page.waitForTimeout(700);
console.log('1. inspecteur sans sélection :', await page.locator('.inspector').count());
await page.screenshot({ path: (process.env.E2E_SHOTS || 'e2e/shots') + '/14-builder-noselect.png' });
await page.locator('.react-flow__node-component').nth(2).click(); await page.waitForTimeout(400);
console.log('2. composant :', (await page.locator('.inspector .panel-title').innerText()), '| tokens:', await page.locator('.inspector .tok-list > div').count());
await page.locator('.inspector input').first().fill('Sign in'); await page.waitForTimeout(200);
await page.screenshot({ path: (process.env.E2E_SHOTS || 'e2e/shots') + '/15-inspector-comp.png' });
await page.locator('.react-flow__node-stack', { hasText: 'Button Group' }).click(); await page.waitForTimeout(300);
await page.locator('.inspector input[aria-label="Pattern name"]').fill('Button Group');
await page.locator('.inspector button:has-text("Save")').click(); await page.waitForTimeout(300);
console.log('3. pattern :', await page.locator('.inspector .note').filter({ hasText: 'Pattern' }).first().innerText());
await page.locator('.palette-item.pattern').first().dblclick(); await page.waitForTimeout(600);
console.log('4. sélection après ajout :', await page.locator('.inspector .eyebrow').innerText());
await page.locator('.inspector input').nth(1).fill('Book my seat'); await page.waitForTimeout(200);
await page.screenshot({ path: (process.env.E2E_SHOTS || 'e2e/shots') + '/16-inspector-pattern.png' });
const src = await page.locator('.react-flow__node-pattern .react-flow__handle-right').boundingBox();
const dst = await page.locator('.react-flow__node-screen .react-flow__handle-left').boundingBox();
await page.mouse.move(src.x + 4, src.y + 4); await page.mouse.down(); await page.mouse.move(dst.x + 4, dst.y + 4, { steps: 12 }); await page.mouse.up(); await page.waitForTimeout(300);
await page.locator('.react-flow__node-screen').click(); await page.waitForTimeout(300);
await page.locator('.inspector button:has-text("JSX")').click();
console.log('5.', (await page.locator('.inspector pre').innerText()).split('\n').filter(l => /ButtonGroup|Sign in/.test(l)).join(' | '));
await page.locator('.inspector button:has-text("Preview")').click(); await page.waitForTimeout(200);
await page.screenshot({ path: (process.env.E2E_SHOTS || 'e2e/shots') + '/17-inspector-screen.png' });
await page.locator('.react-flow__pane').click({ position: { x: 20, y: 300 } }); await page.waitForTimeout(300);
console.log('6. après clic dans le vide :', await page.locator('.inspector').count());
console.log(errors.join('\n') || 'no errors');
await browser.close();
