import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
const W = ms => p.waitForTimeout(ms);
const ok = (n, c) => console.log(c ? 'OK  ' : 'FAIL', n);
await p.goto((process.env.E2E_URL || 'http://localhost:4175') + '/'); await W(1200);
const pages = p.locator('.side-page'), items = p.locator('.side-item');
ok('pages repliées sauf la courante', await p.locator('.side-page[aria-expanded="true"]').count() === 1 && await items.count() === 4);
ok('page courante = Buttons', /Buttons/.test(await p.locator('.side-page[aria-expanded="true"]').innerText()));
await pages.filter({ hasText: 'Cards' }).click(); ok('déplier Cards', await items.count() > 4);
await pages.filter({ hasText: 'Cards' }).click(); ok('replier Cards', await items.count() === 4);
await p.getByRole('button', { name: /^Components/ }).click(); await p.getByRole('button', { name: /^Compositions/ }).click();
ok('filtre Screens seul : une page', await pages.count() === 1 && /Composition guide/.test(await pages.first().innerText()));
await p.getByRole('button', { name: /^Screens/ }).click(); // dernier actif : ignoré
ok('dernier filtre non désactivable', await pages.count() === 1);
await p.getByRole('button', { name: /^Compositions/ }).click();
await p.locator('.search').fill('hero'); await W(200);
ok('recherche déplie et filtre', await pages.count() === 1 && await items.count() > 0);
await p.locator('.search').fill('');
await p.getByRole('button', { name: /^Components/ }).click(); await p.getByRole('button', { name: /^Screens/ }).click();
await pages.filter({ hasText: 'Sections' }).click();
ok('sous-titres de section', await p.locator('.side-sub .side-title').count() > 1);
await p.getByRole('button', { name: /^Screens/ }).click(); await p.getByRole('button', { name: /^Components/ }).click();
await pages.filter({ hasText: 'Composition guide' }).click();
await p.locator('.side-item', { hasText: 'Filter Bar' }).click(); await W(900);
ok('écran ouvre le panneau au niveau Usage', await p.locator('aside.panel[data-open="true"]').count() === 1);
await p.screenshot({ path: (process.env.E2E_SHOTS || 'e2e/shots') + '/sidebar1.png' });
ok('no console errors' + (errs.length ? ': ' + errs.join(' | ') : ''), !errs.length);
await b.close();
