import { chromium } from 'playwright-core';
const o = (process.env.E2E_SHOTS || 'e2e/shots');
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
const W = ms => p.waitForTimeout(ms);
const cur = () => p.locator('.dr-step[aria-current="step"] .dr-name').innerText();
const zoom = () => p.locator('.level[data-state="active"] .react-flow__viewport').evaluate(e => new DOMMatrix(getComputedStyle(e).transform).a);
await p.goto((process.env.E2E_URL || 'http://localhost:4175') + '/'); await W(1200);
console.log('rail', await p.locator('.dr-step').allInnerTexts().then(t => t.map(x => x.replace(/\n/g, ' ')).join(' | ')));
console.log('actif', await cur());
await p.keyboard.press('ArrowUp'); await W(900); console.log('↑ actif', await cur());
await p.keyboard.press('ArrowUp'); await W(1500); console.log('↑ actif', await cur(), '· zoom Usage', (await zoom()).toFixed(2));
console.log('cartes compactes', await p.locator('.level[data-state="active"] .fnode.compact').count(), '· current', await p.locator('.level[data-state="active"] .fnode.current').count());
await p.screenshot({ path: o + '/ui2-usage.png' });
await p.locator('.dr-step', { hasText: 'Library' }).click(); await W(1600); console.log('clic rail actif', await cur(), '· zoom Library', (await zoom()).toFixed(2));
await p.screenshot({ path: o + '/ui2-library.png' });
await p.mouse.move(800, 450); await p.mouse.wheel(0, -200); await W(900); console.log('molette actif', await cur());
await p.locator('.dr-step', { hasText: 'Component' }).click(); await W(1200); console.log('retour actif', await cur());
console.log('errors', errs); await b.close();
