// Assemble code.js (exécuté par Figma) : sérialiseur + normalisation partagés avec l'app + logique du plugin,
// abaissé en ES2017 pour le bac à sable des plugins. Usage : node plugin/build.mjs (après npm install dans app/).
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const app = join(here, '..', 'app');
const { build } = createRequire(join(app, 'package.json'))('rolldown');

const src = [
  readFileSync(join(app, 'scan/figma/serialize.js'), 'utf8'),
  readFileSync(join(app, 'scan/normalize.mjs'), 'utf8').replace(/^export /m, ''),
  readFileSync(join(here, 'src/scan.js'), 'utf8'),
].join('\n');
const tmp = join(mkdtempSync(join(tmpdir(), 'dsu-')), 'entry.js');
writeFileSync(tmp, src);
const out = await build({ input: tmp, write: false, transform: { target: 'es2017' }, output: { format: 'iife', minify: false } });
// Sans les annotations //#region (elles contiennent le dossier temporaire) : même sources, même code.js.
const code = out.output[0].code.replace(/^[ \t]*\/\/#(end)?region.*\n/gm, '');
writeFileSync(join(here, 'code.js'), '// Generated by plugin/build.mjs — edit plugin/src/scan.js, app/scan/figma/serialize.js or app/scan/normalize.mjs instead.\n' + code);
console.log(`code.js: ${(code.length / 1024).toFixed(1)} kB`);
