// Generated by plugin/build.mjs — edit plugin/src/scan.js, app/scan/figma/serialize.js or app/scan/normalize.mjs instead.
(function() {

	function _typeof(o) {
		"@babel/helpers - typeof";
		return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function(o) {
			return typeof o;
		} : function(o) {
			return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype ? "symbol" : typeof o;
		}, _typeof(o);
	}

	function toPrimitive(t, r) {
		if ("object" != _typeof(t) || !t) return t;
		var e = t[Symbol.toPrimitive];
		if (void 0 !== e) {
			var i = e.call(t, r || "default");
			if ("object" != _typeof(i)) return i;
			throw new TypeError("@@toPrimitive must return a primitive value.");
		}
		return ("string" === r ? String : Number)(t);
	}

	function toPropertyKey(t) {
		var i = toPrimitive(t, "string");
		return "symbol" == _typeof(i) ? i : i + "";
	}

	function _defineProperty(e, r, t) {
		return (r = toPropertyKey(r)) in e ? Object.defineProperty(e, r, {
			value: t,
			enumerable: !0,
			configurable: !0,
			writable: !0
		}) : e[r] = t, e;
	}

	function ownKeys(e, r) {
		var t = Object.keys(e);
		if (Object.getOwnPropertySymbols) {
			var o = Object.getOwnPropertySymbols(e);
			r && (o = o.filter(function(r) {
				return Object.getOwnPropertyDescriptor(e, r).enumerable;
			})), t.push.apply(t, o);
		}
		return t;
	}
	function _objectSpread2(e) {
		for (var r = 1; r < arguments.length; r++) {
			var t = null != arguments[r] ? arguments[r] : {};
			r % 2 ? ownKeys(Object(t), !0).forEach(function(r) {
				_defineProperty(e, r, t[r]);
			}) : Object.getOwnPropertyDescriptors ? Object.defineProperties(e, Object.getOwnPropertyDescriptors(t)) : ownKeys(Object(t)).forEach(function(r) {
				Object.defineProperty(e, r, Object.getOwnPropertyDescriptor(t, r));
			});
		}
		return e;
	}

	const hex = (c) => "#" + [
		c.r,
		c.g,
		c.b
	].map((v) => Math.round(v * 255).toString(16).padStart(2, "0")).join("").toUpperCase();
	const TYPE = {
		COMPONENT: "Com",
		INSTANCE: "Ins",
		FRAME: "Fra",
		TEXT: "Tex",
		ELLIPSE: "Ell",
		RECTANGLE: "Rec",
		VECTOR: "Vec",
		GROUP: "Fra",
		BOOLEAN_OPERATION: "Vec",
		LINE: "Vec",
		STAR: "Vec",
		POLYGON: "Vec",
		COMPONENT_SET: "Fra",
		SLOT: "Slo"
	};
	const AX = {
		MIN: "MN",
		CENTER: "CR",
		MAX: "MX",
		SPACE_BETWEEN: "SN",
		BASELINE: "BE"
	};
	const round = (v) => Math.round(v * 100) / 100;
	const paints = (arr, bound) => {
		if (!Array.isArray(arr)) return void 0;
		const out = [];
		arr.forEach((p, i) => {
			if (p.visible === false) return;
			if (p.type === "SOLID") {
				var _p$boundVariables;
				const o = { c: hex(p.color) };
				if (p.opacity !== void 0 && p.opacity < 1) o.o = round(p.opacity);
				const v = (_p$boundVariables = p.boundVariables) === null || _p$boundVariables === void 0 || (_p$boundVariables = _p$boundVariables.color) === null || _p$boundVariables === void 0 ? void 0 : _p$boundVariables.id;
				if (v) o.v = v.replace(/^VariableID:/, "");
				out.push(o);
			} else if (p.type === "IMAGE") out.push({ img: 1 });
			else if (p.type.startsWith("GRADIENT")) out.push({ g: p.gradientStops.map((s) => hex(s.color) + "@" + round(s.position)) });
		});
		return out.length ? out : void 0;
	};
	const BOUND_KEYS = [
		"itemSpacing",
		"paddingLeft",
		"paddingTop",
		"paddingRight",
		"paddingBottom",
		"topLeftRadius",
		"topRightRadius",
		"bottomLeftRadius",
		"bottomRightRadius",
		"strokeWeight",
		"width",
		"height",
		"fontSize",
		"fontFamily",
		"fontWeight",
		"lineHeight",
		"letterSpacing",
		"minWidth",
		"maxWidth",
		"opacity"
	];
	const ICONS = {};
	async function iconBody(node) {
		try {
			return (await node.exportAsync({ format: "SVG_STRING" })).replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").replace(/\s+/g, " ").trim();
		} catch (e) {
			return;
		}
	}
	async function ser(n, isRoot, opts) {
		if (n.visible === false) return null;
		const o = {
			t: TYPE[n.type] || "Fra",
			n: n.name,
			w: round(n.width),
			h: round(n.height)
		};
		const parentAuto = n.parent && "layoutMode" in n.parent && n.parent.layoutMode !== "NONE" && n.layoutPositioning !== "ABSOLUTE";
		if (!isRoot && !parentAuto) {
			o.x = round(n.x);
			o.y = round(n.y);
		}
		if (!isRoot && "layoutSizingHorizontal" in n) {
			o.sh = n.layoutSizingHorizontal === "HUG" ? "H" : "F";
			o.sv = n.layoutSizingVertical === "HUG" ? "H" : "F";
		}
		if ("opacity" in n && n.opacity < 1) o.op = round(n.opacity);
		const b = {};
		const bv = n.boundVariables || {};
		for (const k of BOUND_KEYS) {
			var _x$;
			const x = bv[k];
			const id = Array.isArray(x) ? (_x$ = x[0]) === null || _x$ === void 0 ? void 0 : _x$.id : x === null || x === void 0 ? void 0 : x.id;
			if (id) b[k] = id.replace(/^VariableID:/, "");
		}
		if (n.type === "INSTANCE") {
			const mc = await n.getMainComponentAsync();
			if (mc) {
				var _mc$parent;
				const set = ((_mc$parent = mc.parent) === null || _mc$parent === void 0 ? void 0 : _mc$parent.type) === "COMPONENT_SET" ? mc.parent : null;
				o.ref = (set || mc).id;
				if (set) o.var = mc.id;
				if (opts.iconPages.includes(await pageOf(mc))) {
					const key = (set ? set.name + "/" + mc.name : mc.name) + "@" + Math.round(n.width);
					if (!(key in ICONS)) ICONS[key] = await iconBody(n);
					o.icon = key;
					const solid = (k) => (x) => k in x && Array.isArray(x[k]) && x[k].some((p) => p.type === "SOLID" && p.visible !== false);
					const fillNode = n.findOne(solid("fills")), strokeNode = fillNode ? null : n.findOne(solid("strokes"));
					const col = fillNode || strokeNode;
					if (col) {
						var _p$boundVariables2;
						const p = col[fillNode ? "fills" : "strokes"].find((p) => p.type === "SOLID" && p.visible !== false);
						o.ic = hex(p.color);
						const v = (_p$boundVariables2 = p.boundVariables) === null || _p$boundVariables2 === void 0 || (_p$boundVariables2 = _p$boundVariables2.color) === null || _p$boundVariables2 === void 0 ? void 0 : _p$boundVariables2.id;
						if (v) o.icv = v.replace(/^VariableID:/, "");
					}
					if (Object.keys(b).length) o.b = b;
					return o;
				}
			}
		}
		if (n.type === "TEXT") {
			const f = paints(n.fills);
			if (f) o.f = f;
			const fn = n.fontName === figma.mixed ? n.getRangeFontName(0, 1) : n.fontName;
			const fs = n.fontSize === figma.mixed ? n.getRangeFontSize(0, 1) : n.fontSize;
			const lh = n.lineHeight === figma.mixed ? n.getRangeLineHeight(0, 1) : n.lineHeight;
			const ls = n.letterSpacing === figma.mixed ? n.getRangeLetterSpacing(0, 1) : n.letterSpacing;
			o.tx = {
				c: n.characters,
				fs,
				ff: fn.family,
				st: fn.style,
				lh: lh.unit === "AUTO" ? null : lh.unit === "PERCENT" ? lh.value + "%" : lh.value,
				ls: ls.unit === "PERCENT" ? round(ls.value / 100) : round(ls.value / (fs || 16)),
				al: {
					LEFT: "L",
					CENTER: "C",
					RIGHT: "R",
					JUSTIFIED: "J"
				}[n.textAlignHorizontal] || "L",
				ar: n.textAutoResize === "WIDTH_AND_HEIGHT" ? "W" : n.textAutoResize === "HEIGHT" ? "H" : "N"
			};
			if (Object.keys(b).length) o.b = b;
			return o;
		}
		if ([
			"VECTOR",
			"BOOLEAN_OPERATION",
			"LINE",
			"STAR",
			"POLYGON"
		].includes(n.type)) {
			o.svg = await iconBody(n);
			if (Object.keys(b).length) o.b = b;
			return o;
		}
		const f = paints(n.fills);
		if (f) o.f = f;
		const s = paints(n.strokes);
		if (s) {
			o.s = s;
			if (n.strokeWeight !== figma.mixed) o.sw = round(n.strokeWeight);
			if ("strokeTopWeight" in n) {
				const w = [
					n.strokeTopWeight,
					n.strokeRightWeight,
					n.strokeBottomWeight,
					n.strokeLeftWeight
				];
				if (n.strokeWeight === figma.mixed || w.some((x) => x !== n.strokeWeight)) o.sws = w.map(round);
			}
		}
		if ("cornerRadius" in n) {
			if (n.cornerRadius === figma.mixed) o.r = [
				n.topLeftRadius,
				n.topRightRadius,
				n.bottomRightRadius,
				n.bottomLeftRadius
			].map(round);
			else if (n.cornerRadius) o.r = round(n.cornerRadius);
		}
		if ("effects" in n && n.effects.length) {
			const fx = n.effects.filter((e) => e.visible !== false && (e.type === "DROP_SHADOW" || e.type === "INNER_SHADOW")).map((e) => [
				e.type === "INNER_SHADOW" ? "I" : "D",
				round(e.offset.x),
				round(e.offset.y),
				round(e.radius),
				round(e.spread || 0),
				hex(e.color),
				round(e.color.a)
			]);
			if (fx.length) o.fx = fx;
		}
		if ("layoutMode" in n && n.layoutMode !== "NONE") o.lay = [
			n.layoutMode === "HORIZONTAL" ? "H" : "V",
			n.primaryAxisAlignItems === "SPACE_BETWEEN" ? 0 : round(n.itemSpacing),
			round(n.paddingTop),
			round(n.paddingRight),
			round(n.paddingBottom),
			round(n.paddingLeft),
			AX[n.primaryAxisAlignItems] || "MN",
			AX[n.counterAxisAlignItems] || "MN",
			n.layoutWrap === "WRAP" ? 1 : 0
		];
		if ("clipsContent" in n && n.clipsContent && (n.type === "FRAME" || n.type === "COMPONENT" || n.type === "INSTANCE")) o.clip = 1;
		if (Object.keys(b).length) o.b = b;
		if ("children" in n) {
			const kids = [];
			for (const c of n.children) {
				if (opts.budget.n-- <= 0) break;
				const k = await ser(c, false, opts);
				if (k) kids.push(k);
			}
			if (kids.length) o.c = kids;
		}
		return o;
	}
	async function pageOf(node) {
		let p = node;
		while (p && p.type !== "PAGE") p = p.parent;
		return p ? p.name : "";
	}
	function normalize({ vars, pages, screens = [], iconsPage = null, file, layers, layerOf, slotSurvey = {} }) {
		var _c$name, _byName$_c$name;
		const internal = (name) => /^[_.]/.test(name);
		const TYPES = {
			C: "COLOR",
			F: "FLOAT",
			S: "STRING",
			B: "BOOLEAN"
		};
		const parseVal = (raw) => {
			if (raw.startsWith("@")) return { alias: raw.slice(1) };
			if (raw.startsWith("#")) return raw;
			try {
				return JSON.parse(raw);
			} catch (_unused) {
				return raw;
			}
		};
		const collections = Object.fromEntries(vars.collections.map((c) => [c.id, {
			id: c.id,
			name: c.name,
			modes: c.modes.map(([id, name]) => ({
				id,
				name
			})),
			orphan: false
		}]));
		const variables = {};
		for (const [id, name, t, col, code, vals] of vars.rows) {
			const values = {};
			const pairs = Array.isArray(vals) ? vals : vals.split("|").map((part) => {
				const i = part.indexOf("=");
				return i > 0 ? [part.slice(0, i), part.slice(i + 1)] : null;
			}).filter(Boolean);
			for (const [m, raw] of pairs) values[m] = parseVal(raw);
			variables[id] = {
				id,
				name,
				type: TYPES[t],
				collection: col,
				css: code ? code.replace(/^var\(--(.*?)(,.*)?\)$/, "$1") : "",
				values,
				local: true
			};
		}
		const parseVariantName = (n) => Object.fromEntries(n.split(",").map((s) => s.trim().split("=")).filter((p) => p.length === 2));
		const icons = {};
		const components = {};
		for (const j of pages) {
			Object.assign(icons, Object.fromEntries(Object.entries(j.icons || {}).filter(([, b]) => typeof b === "string" && b.length)));
			for (const c of j.components) {
				var _j$trees;
				if (internal(c.name)) continue;
				const t = (_j$trees = j.trees) === null || _j$trees === void 0 ? void 0 : _j$trees[c.id];
				let variants = [];
				if (t && t.t) variants = [{
					id: c.id,
					name: c.name,
					props: {},
					tree: t
				}];
				else if (t) variants = Object.entries(t).map(([vid, tree]) => ({
					id: vid,
					name: tree.n,
					props: parseVariantName(tree.n),
					tree
				}));
				const uses = Object.entries(c.uses || {}).map(([k, count]) => {
					const i = k.indexOf("|");
					return {
						id: k.slice(0, i),
						name: k.slice(i + 1),
						count
					};
				});
				components[c.id] = _objectSpread2(_objectSpread2({
					id: c.id,
					kind: c.kind,
					page: c.page,
					name: c.name,
					description: c.desc || "",
					props: c.props,
					variantCount: c.variants,
					variants,
					uses,
					group: c.group || c.page
				}, layerOf ? { layer: layerOf(c.page) } : {}), {}, {
					key: c.key,
					slots: Object.entries(Object.fromEntries(Object.entries(c.pref || {}).filter(([, d]) => d.slot))).concat(Object.entries(slotSurvey[c.id] || {})).reduce((acc, [name, d]) => acc.some((x) => x.name === name) ? acc : [...acc, {
						name,
						prefKeys: d.pref || [],
						desc: d.desc || ""
					}], [])
				});
			}
		}
		const byName = {};
		for (const c of Object.values(components)) ((_byName$_c$name = byName[_c$name = c.name]) !== null && _byName$_c$name !== void 0 ? _byName$_c$name : byName[_c$name] = []).push(c.id);
		const remap = (u) => {
			var _byName$u$name;
			return components[u.id] ? u : ((_byName$u$name = byName[u.name]) === null || _byName$u$name === void 0 ? void 0 : _byName$u$name.length) === 1 ? _objectSpread2(_objectSpread2({}, u), {}, { id: byName[u.name][0] }) : null;
		};
		const stats = {
			remapped: 0,
			dropped: 0,
			slots: 0,
			prefs: 0
		};
		for (const c of Object.values(components)) {
			const merged = {};
			for (const u of c.uses) {
				const r = remap(u);
				if (!r) {
					stats.dropped++;
					continue;
				}
				if (r.id !== u.id) stats.remapped++;
				if (r.id === c.id) continue;
				merged[r.id] = merged[r.id] ? _objectSpread2(_objectSpread2({}, r), {}, { count: merged[r.id].count + r.count }) : r;
			}
			c.uses = Object.values(merged);
		}
		const byKey = Object.fromEntries(Object.values(components).filter((c) => c.key).map((c) => [c.key, c.id]));
		for (const c of Object.values(components)) {
			c.slots = c.slots.map(({ name, prefKeys, desc }) => {
				const pref = prefKeys.map((k) => byKey[k]).filter(Boolean);
				stats.slots++;
				stats.prefs += pref.length;
				return _objectSpread2({
					name,
					pref
				}, desc ? { desc } : {});
			});
			if (!c.slots.length) delete c.slots;
			delete c.key;
		}
		const out = [];
		const seen = /* @__PURE__ */ new Set();
		for (const s of screens) {
			if (seen.has(s.id) || components[s.id]) continue;
			seen.add(s.id);
			out.push(_objectSpread2(_objectSpread2({}, s), {}, { uses: Object.entries(s.uses).map(([k, count]) => {
				const i = k.indexOf("|");
				return remap({
					id: k.slice(0, i),
					name: k.slice(i + 1),
					count
				});
			}).filter(Boolean) }));
		}
		return {
			library: _objectSpread2({
				schema: 1,
				file,
				collections,
				variables,
				components,
				screens: out,
				icons,
				iconsPage: iconsPage ? {
					page: iconsPage.page,
					components: iconsPage.components,
					groups: iconsPage.groups
				} : {
					page: "",
					components: 0,
					groups: {}
				}
			}, layers ? { layers } : {}),
			stats
		};
	}
	const MAX_VARIANTS = 12;
	const ALL_VARIANTS = 48;
	const NODE_BUDGET = 700;
	const cleanKey = (k) => k.replace(/#[\d:]+$/, "");
	const isIconPage = (name) => /icon/i.test(name);
	const pageOfNode = (n) => {
		let p = n;
		while (p && p.type !== "PAGE") p = p.parent;
		return p;
	};
	const ownerOf = (mc) => {
		var _mc$parent2;
		return ((_mc$parent2 = mc.parent) === null || _mc$parent2 === void 0 ? void 0 : _mc$parent2.type) === "COMPONENT_SET" ? mc.parent : mc;
	};
	const progress = (text, ratio) => figma.ui.postMessage({
		type: "progress",
		text,
		ratio
	});
	function pickVariants(s, all) {
		if (s.type !== "COMPONENT_SET") return [s];
		let vs = s.children.filter((c) => c.type === "COMPONENT");
		if (all) return vs.slice(0, ALL_VARIANTS);
		const defs = s.componentPropertyDefinitions;
		const stateKey = Object.keys(defs).find((k) => defs[k].type === "VARIANT" && /^(state|status|interaction)$/i.test(k));
		if (stateKey) {
			const def = defs[stateKey].defaultValue;
			const keep = vs.filter((v) => {
				var _v$variantProperties;
				return ((_v$variantProperties = v.variantProperties) === null || _v$variantProperties === void 0 ? void 0 : _v$variantProperties[stateKey]) === def;
			});
			if (keep.length) vs = keep;
		}
		const dv = s.defaultVariant;
		if (dv) vs = [dv, ...vs.filter((v) => v !== dv)];
		return vs.slice(0, MAX_VARIANTS);
	}
	async function scanSet(s, iconPages, allVariants) {
		const page = pageOfNode(s);
		const defs = s.componentPropertyDefinitions;
		const props = {}, pref = {};
		for (const [k, d] of Object.entries(defs)) {
			props[cleanKey(k)] = d.type === "VARIANT" ? d.variantOptions : d.type;
			const keys = (d.preferredValues || []).filter((p) => p.type === "COMPONENT" || p.type === "COMPONENT_SET").map((p) => p.key).slice(0, 40);
			if (d.type === "SLOT") pref[cleanKey(k)] = {
				slot: 1,
				pref: keys,
				prefCount: (d.preferredValues || []).length,
				desc: d.description || ""
			};
			if (d.type === "INSTANCE_SWAP") pref[cleanKey(k)] = {
				def: d.defaultValue,
				pref: keys,
				prefCount: (d.preferredValues || []).length
			};
		}
		const uses = {};
		const variants = s.type === "COMPONENT_SET" ? s.children : [s];
		for (const v of variants) {
			const seen = /* @__PURE__ */ new Set();
			for (const ins of v.findAllWithCriteria({ types: ["INSTANCE"] })) {
				const mc = await ins.getMainComponentAsync();
				if (!mc) continue;
				const owner = ownerOf(mc);
				if (owner.id === s.id || seen.has(owner.id)) continue;
				const p = pageOfNode(owner);
				if (p && isIconPage(p.name)) continue;
				seen.add(owner.id);
				const key = owner.id + "|" + owner.name;
				uses[key] = (uses[key] || 0) + 1;
			}
		}
		let section = s.parent;
		while (section && section.type !== "SECTION" && section.type !== "PAGE") section = section.parent;
		const comp = {
			id: s.id,
			kind: s.type === "COMPONENT_SET" ? "set" : "component",
			page: page ? page.name : "",
			group: section && section.type === "SECTION" ? section.name : "",
			name: s.name,
			desc: s.description || "",
			props,
			pref,
			variants: variants.length,
			key: s.key,
			uses
		};
		const opts = {
			iconPages,
			budget: { n: NODE_BUDGET }
		};
		let tree;
		if (s.type === "COMPONENT_SET") {
			tree = {};
			for (const v of pickVariants(s, allVariants)) {
				opts.budget.n = NODE_BUDGET;
				const t = await ser(v, true, opts);
				if (t) tree[v.id] = t;
			}
		} else tree = await ser(s, true, opts);
		return {
			comp,
			tree
		};
	}
	function scanVars() {
		return (async () => {
			const cols = await figma.variables.getLocalVariableCollectionsAsync();
			const strip = (id) => id.replace(/^VariableCollectionId:|^VariableID:/, "");
			const hexA = (c) => "#" + [
				c.r,
				c.g,
				c.b
			].map((v) => Math.round(v * 255).toString(16).padStart(2, "0")).join("").toUpperCase() + (c.a !== void 0 && c.a < 1 ? Math.round(c.a * 255).toString(16).padStart(2, "0").toUpperCase() : "");
			const T = {
				COLOR: "C",
				FLOAT: "F",
				STRING: "S",
				BOOLEAN: "B"
			};
			const rows = (await figma.variables.getLocalVariablesAsync()).map((v) => {
				var _v$codeSyntax;
				return [
					strip(v.id),
					v.name,
					T[v.resolvedType],
					strip(v.variableCollectionId),
					((_v$codeSyntax = v.codeSyntax) === null || _v$codeSyntax === void 0 ? void 0 : _v$codeSyntax.WEB) || "",
					Object.entries(v.valuesByMode).map(([m, x]) => [m, x && x.type === "VARIABLE_ALIAS" ? "@" + strip(x.id) : v.resolvedType === "COLOR" ? hexA(x) : JSON.stringify(x)])
				];
			});
			return {
				collections: cols.map((c) => ({
					id: strip(c.id),
					name: c.name,
					modes: c.modes.map((m) => [m.modeId, m.name])
				})),
				rows
			};
		})();
	}
	async function scanScreens(page) {
		const frames = [];
		const visit = (n) => {
			for (const c of n.children) if (c.type === "SECTION") visit(c);
			else if (c.type === "FRAME") frames.push(c);
		};
		visit(page);
		const screens = [];
		for (const f of frames) {
			const uses = {};
			for (const ins of f.findAllWithCriteria({ types: ["INSTANCE"] })) {
				const mc = await ins.getMainComponentAsync();
				if (!mc) continue;
				const owner = ownerOf(mc);
				const p = pageOfNode(owner);
				if (!p || isIconPage(p.name)) continue;
				let q = ins.parent, nested = false;
				while (q && q !== f) {
					if (q.type === "INSTANCE") {
						nested = true;
						break;
					}
					q = q.parent;
				}
				if (nested) continue;
				const key = owner.id + "|" + owner.name;
				uses[key] = (uses[key] || 0) + 1;
			}
			if (Object.keys(uses).length) screens.push({
				id: f.id,
				page: page.name,
				name: f.name,
				w: Math.round(f.width),
				h: Math.round(f.height),
				uses
			});
		}
		return screens;
	}
	function iconsSummary(page) {
		const comps = page.findAllWithCriteria({ types: ["COMPONENT"] });
		const groups = {};
		for (const c of comps) {
			let s = c.parent;
			while (s && s.type !== "SECTION" && s.type !== "FRAME" && s.type !== "PAGE") s = s.parent;
			const g = s && s.type !== "PAGE" ? s.name : page.name;
			groups[g] = (groups[g] || 0) + 1;
		}
		return {
			page: page.name,
			components: comps.length,
			groups
		};
	}
	const setsOnPage = (page) => page.findAllWithCriteria({ types: ["COMPONENT_SET", "COMPONENT"] }).filter((n) => n.type === "COMPONENT_SET" || n.parent.type !== "COMPONENT_SET");
	async function setsFromSelection() {
		const out = /* @__PURE__ */ new Map();
		for (const n of figma.currentPage.selection) if (n.type === "COMPONENT_SET") out.set(n.id, n);
		else if (n.type === "COMPONENT") {
			const o = ownerOf(n);
			out.set(o.id, o);
		} else if (n.type === "INSTANCE") {
			const mc = await n.getMainComponentAsync();
			if (mc) {
				const o = ownerOf(mc);
				out.set(o.id, o);
			}
		} else if ("findAllWithCriteria" in n) for (const s of n.findAllWithCriteria({ types: ["COMPONENT_SET", "COMPONENT"] })) {
			const o = ownerOf(s);
			out.set(o.id, o);
		}
		return [...out.values()];
	}
	async function run(scope, fileUrl) {
		var _match;
		for (const k of Object.keys(ICONS)) delete ICONS[k];
		await figma.loadAllPagesAsync();
		const pagesAll = figma.root.children;
		const iconPages = pagesAll.filter((p) => isIconPage(p.name)).map((p) => p.name);
		let sets = [], screenPages = [];
		if (scope === "selection") {
			sets = await setsFromSelection();
			if (!sets.length) throw new Error("Select a component, a component set, an instance, or a frame that contains components.");
		} else if (scope === "page") {
			sets = setsOnPage(figma.currentPage);
			screenPages = [figma.currentPage];
		} else {
			for (const p of pagesAll) if (!isIconPage(p.name)) sets.push(...setsOnPage(p));
			screenPages = pagesAll.filter((p) => !isIconPage(p.name));
		}
		if (!sets.length) throw new Error("No components found here.");
		progress("Reading variables…", 0);
		const vars = await scanVars();
		const components = [], trees = {};
		for (let i = 0; i < sets.length; i++) {
			const s = sets[i];
			progress(`Component ${i + 1} / ${sets.length} · ${s.name}`, (i + 1) / (sets.length + 1));
			const { comp, tree } = await scanSet(s, iconPages, scope === "selection");
			components.push(comp);
			if (tree) trees[s.id] = tree;
		}
		const screens = [];
		for (const p of screenPages) {
			progress(`Screens on ${p.name}…`, .98);
			screens.push(...await scanScreens(p));
		}
		const iconPage = pagesAll.find((p) => isIconPage(p.name));
		const fromUrl = (_match = (fileUrl || "").match(/figma\.com\/(?:design|file)\/([A-Za-z0-9]+)/)) === null || _match === void 0 ? void 0 : _match[1];
		const key = figma.fileKey || fromUrl || "";
		const { library, stats } = normalize({
			vars,
			pages: [{
				components,
				trees,
				icons: ICONS
			}],
			screens,
			iconsPage: iconPage ? iconsSummary(iconPage) : null,
			file: {
				key,
				name: figma.root.name,
				scannedAt: (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
				via: `DS Universe Scanner (${scope})`
			}
		});
		const rendered = Object.values(library.components).filter((c) => c.variants.length).length;
		return {
			library,
			summary: {
				components: Object.keys(library.components).length,
				rendered,
				variables: Object.keys(library.variables).length,
				screens: library.screens.length,
				icons: Object.keys(library.icons).length,
				dropped: stats.dropped,
				key: !!key
			}
		};
	}
	figma.showUI(__html__, {
		width: 360,
		height: 460,
		themeColors: true
	});
	const sendSelection = () => figma.ui.postMessage({
		type: "selection",
		count: figma.currentPage.selection.length,
		page: figma.currentPage.name,
		file: figma.root.name,
		hasKey: !!figma.fileKey
	});
	figma.on("selectionchange", sendSelection);
	figma.on("currentpagechange", sendSelection);
	sendSelection();
	figma.ui.onmessage = async (msg) => {
		if (msg.type !== "scan") return;
		try {
			const { library, summary } = await run(msg.scope, msg.fileUrl);
			figma.ui.postMessage({
				type: "done",
				json: JSON.stringify(library),
				summary,
				name: figma.root.name
			});
		} catch (e) {
			figma.ui.postMessage({
				type: "error",
				text: e instanceof Error ? e.message : String(e)
			});
		}
	};

})();